DROP DATABASE IF EXISTS employee_tracker_db;
CREATE DATABASE employee_tracker_db;

USE employee_tracker_db;

CREATE TABLE departments (
  dept_name VARCHAR(30) NOT NULL,   
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date_updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE roles (
    title VARCHAR(30) NOT NULL, 
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    department VARCHAR(30) NOT NULL, 
    salary DECIMAL UNSIGNED NOT NULL,
    date_updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE employees (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL, 
    last_name VARCHAR(30) NOT NULL, 
    job_title VARCHAR(30) NOT NULL, 
    department VARCHAR(30) NOT NULL, 
    salary DECIMAL UNSIGNED NOT NULL,
    managers VARCHAR(30) NOT NULL,
    date_updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);